### PR TITLE
bug/record-handler: Fixes #140

### LINKED ISSUE #140: snapshot should wait for isReady
```
RecordHandler.prototype.snapshot = function( name, callback ) {
    if( this._records[ name ] && this._records[ name ].isReady ) {
       callback(null, this._records[ name ].get() );
    } else {
        this._snapshotRegistry.request( name, callback );
    }
};

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
This is missing a corresponding unit test.

**Comment by yasserf** [comment]
@ronag we are currently looking into creating a contributing guide and a terms/conditions before we merge any more PRs. I'll send you that next week.

**Comment by ronag** [comment]
@yasserf

**Comment by yasserf** [comment]
Merging this in this week

**Pull request closed without merging**
