### PR TITLE
Add presence to d.ts

### PR DESCRIPTION
**Pull request by benjaminVadon**
Add Presence interface
Add presence field in Client

### CODE REVIEW

**Comment by benjaminVadon** [comment]
I don't understand for tests.
It seems that tests were well passed a first time, and then tests failed for in a second time.

**Comment by yasserf** [comment]
Probably just a timeout, we have a few hundred e2e tests passing so its a bit unavoidable :$

Thanks for the PR, once it restarts will merge. Says here your not yet a contributor, would you mind signing the CLA? https://deepstream.io/info/community/cla/ Thanks!

**Comment by yasserf** [comment]
Tests pass, woot! 

I'll be doing a release today, but can do another patch release once this is in

**Comment by benjaminVadon** [comment]
No problem for the CLA, I will it. But your link  redirect to https://deepstream.io/info/community/cla/form-ready with a  content Not Found...

**Comment by yasserf** [comment]
Seems like a type-form regression =(

I'll merge in and once form is back working will give you a nudge, thanks!

**Pull request merged**
