### PR TITLE
delete doubled Action constant

### PR DESCRIPTION
**Pull request by schulz3000**
Action constant for Q Query is doubled

### CODE REVIEW

**Comment by yasserf** [comment]
Would you be okay with signing our CLA?

https://deepstream.typeform.com/to/PwwNd5

And many thanks for the PR(s)!

**Comment by yasserf** [comment]
Small reminder, be awesome if you could sign the CLA, we can't merge anything in without it =(

https://deepstream.typeform.com/to/PwwNd5

**Comment by schulz3000** [comment]
@yasserf  signed the CLA

**Comment by yasserf** [comment]
Awesome, thanks!

**Pull request merged**
